### ISSUE TITLE
Database installation does not execute to the end

### ISSUE THREAD

**Issue by wadaki** [limbas/limbas#1]
There is no problem during installation, but on the last step it will stopping the process. With sample data or not, the installation will be not complete. Any ideas?

![20230713_152429_](https://github.com/limbas/limbas/assets/8577568/65991ad9-b9f5-4f8e-85d5-6e17dbcbcde3)
![20230713_152413_](https://github.com/limbas/limbas/assets/8577568/ddef04f6-0330-4308-93d2-3e81f021fa95)
![20230713_152357_](https://github.com/limbas/limbas/assets/8577568/b08cf7a5-7ce6-40fd-9445-a3ca00aced57)
![20230713_152324_](https://github.com/limbas/limbas/assets/8577568/5819d2e9-9155-471c-898c-b61df68d54d6)
![20230713_152311_](https://github.com/limbas/limbas/assets/8577568/334e5e98-2248-4d64-a26f-36ceb7ede42d)
![20230713_152246_](https://github.com/limbas/limbas/assets/8577568/6b6f38a3-edc4-43b7-9acf-a403fd0eb369)
![20230713_152230_](https://github.com/limbas/limbas/assets/8577568/079b243e-d6fb-4ef7-9835-8d1affca65cb)

**Comment by limbas** [comment]
If you tried to install the demo, it was because the demo file was corrupt. See  #5
