### ISSUE TITLE
Unable to install demo (demo.tar.gz), trying with 5.2.14

### ISSUE THREAD

**Issue by elmarbransch** [limbas/limbas#5]
I tried to install Limbas with local httpd, online on some shared host and local with Docker. I succeded on each of the three platforms, but failed to install the demo on any of the three.
I tried to choose "demo" while installation, that make the installation fail after the third or fourth step .. depending on my environment.
On the other hand: I installed with a clean profile and tried to import demo.tar.gz, in this case it fails in the same way as if I tried to install the demo profile initially and in addition my installation is broken afterward...
The failures always appeared around the "stored procedures" step, either with the step (red) or after the step (green).

The version I tried was 5.2.14.

If I look at demo.tar.gz inside "dependent/BACKUP", it seems to be only a gzip archive, but not a tar.gz.not sure if this is an issue for the app.

Any idea how to overcome this issue?

**Comment by bhoesel** [comment]
Had a similar experience. Looking at the demo.tar.gz file is shows is not a tar but a gzipped postgresql dump file. Tried to install that one into an empty postgresql public schema but that did not result in the demo data being loaded it seemed an initial Limbas environment was created. So for now no demo environment for 5.2.14. I tried to fallback to 5.1.12 but that has a php error that shows some js text on every page. Running on ubuntu 20.04 and php 8.1.

Please provide a correct demo.tar.gz for 5.2.14.

**Comment by limbas** [comment]
Unfortunately, the demo file in the previous release was corrupt and therefore could not be fully unpacked. The new [version 5.3.12](https://github.com/limbas/limbas/releases/tag/v5.3.12) has a working demo again. Please note that the demo is really only a demo. For your own projects you should always start with an empty installation.
