### ISSUE TITLE
Security contact 

### ISSUE THREAD

**Issue by mal-tee** [limbas/limbas#6]
Hello maintainer(s),

I am a security researcher from the Institute of Application Security at TU Braunschweig, Germany. We discovered a (potential) security vulnerability in your project.

We would like to report this vulnerability to you in a responsible and ethical manner.
Therefore, we do not want to disclose any details of the vulnerability publicly until you have had a chance to review and fix it.

Could you please let us know your prefered way of receiving security reports?

You can contact us at [ias-disclosure@tu-braunschweig.de](mailto:ias-disclosure@tu-braunschweig.de) or by replying to this issue.

Thank you for your attention and cooperation.

**Comment by limbas** [comment]
Thank you for your information. The affected part of the code was outdated and unused and was removed in version 5.2.14. Versions prior to version 5.2.14 should no longer be used.
