### ISSUE TITLE
Error while running docker-compose command.

### ISSUE THREAD

**Issue by mccleod1290** [limbas/limbas#7]
```bash
┌─[mccleod@parrot]─[~/work/test/limbas/]
└──╼ $docker-compose up 
limbas_limbas_pgsql_1 is up-to-date
Starting 0ed8666c3140_limbas_limbas_web_1 ... error

ERROR: for 0ed8666c3140_limbas_limbas_web_1  Cannot start service limbas_web: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "docker-entrypoint.sh": executable file not found in $PATH: unknown

ERROR: for limbas_web  Cannot start service limbas_web: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "docker-entrypoint.sh": executable file not found in $PATH: unknown
ERROR: Encountered errors while bringing up the project.

```

I tried to put this `docker-entrypoint.sh` to path, and also i tried to stop the container and then again restart, and also I gave it executable permissions, and ran the command `docker-compose up --force-recreate limbas_web`, but nothing worked could anyone help me out.

**Comment by limbas** [comment]
The error indicates that the underlying architecture is not compatible with the image because our previous images were only built for one platform.
The new version is now built for different platforms. It should now work from [version 5.3.12](https://github.com/limbas/limbas/releases/tag/v5.3.12).
